# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Organization.destroy_all

Organization.create(name: "Area Neighborhood Commission 3F", orgtype: "community")
Organization.create(name: "Asian Pacific American Labor Alliance - DC Chapter", orgtype: "local")
Organization.create(name: "Brennan Center for Justice", orgtype: "national")
Organization.create(name: "Code Pink DC", orgtype: "local")
Organization.create(name: "Communication Workers of America", orgtype: "national")
Organization.create(name: "Sierra Club - DC Chapter", orgtype: "local")
Organization.create(name: "DC 350.org", orgtype: "local")
Organization.create(name: "DC Area Transmasculine Society", orgtype: "local")
Organization.create(name: "DC Coalition for Housing Justice", orgtype: "coalition-local")
Organization.create(name: "DC Divest", orgtype: "local")
Organization.create(name: "DC Environmental Network", orgtype: "coalition-local")
Organization.create(name: "DC Fair Budget Coalition", orgtype: "coalition-local")
Organization.create(name: "DC for Democracy", orgtype: "local")
Organization.create(name: "Jews United for Justice", orgtype: "local")
Organization.create(name: "DC Jobs with Justice", orgtype: "coalition-local")
Organization.create(name: "DC Latino Caucus", orgtype: "local")
Organization.create(name: "DC Nurses Association", orgtype: "local")
Organization.create(name: "DC Peace Team", orgtype: "local")
Organization.create(name: "DC Solar United Neighborhoods", orgtype: "local")
Organization.create(name: "DC Statehood Green Party", orgtype: "local")
Organization.create(name: "DC Tenants' Rights Center", orgtype: "local")
Organization.create(name: "Food and Water Watch", orgtype: "national")
Organization.create(name: "Franciscan Action Network", orgtype: "national")
Organization.create(name: "Justice First", orgtype: "local")
Organization.create(name: "ONE DC", orgtype: "local")
Organization.create(name: "Pax Christi - Francis of Assisi Community (DC)", orgtype: "local")
Organization.create(name: "People for the American Way", orgtype: "national")
Organization.create(name: "Postive Force DC", orgtype: "local")
Organization.create(name: "Public Citizen", orgtype: "lead")
Organization.create(name: "DC Re-Entry Network", orgtype: "local")
Organization.create(name: "Restaurant Opportunities Center-DC", orgtype: "local")
Organization.create(name: "Service Employees International Union, Local 32BJ", orgtype: "local")
Organization.create(name: "SPACES", orgtype: "local")
Organization.create(name: "Stop Police Terror Project DC", orgtype: "local")
Organization.create(name: "U.S. Public Interest Research Group", orgtype: "national")
Organization.create(name: "United Food and Commercial Workers, Local 400", orgtype: "local")
Organization.create(name: "Washington Ethical Society", orgtype: "local")
Organization.create(name: "We Are Family", orgtype: "local")
Organization.create(name: "William H. Lamar IV, Pastor, Metropolitan AME Church", orgtype: "individual")
Organization.create(name: "The Assisi Community", orgtype: "local")
